# name: igls_new
# description: iGLS Applications.

# publish_to: "none" # Remove this line if you wish to publish to pub.dev

# version: 1.0.29+53 #updated 28/10/2024

# environment:
#   sdk: ">=3.1.0 <4.0.0"

# dependencies:
#   awesome_dialog: ^3.2.1
#   build_runner: ^2.4.9
#   cupertino_icons: ^1.0.8
#   currency_text_input_formatter: ^2.2.3
#   date_format: ^2.0.7
#   device_info_plus: ^9.1.0
#   # dio: ^4.0.6
#   dio: ^5.7.0
#   dropdown_button2: ^2.3.9
#   easy_localization: ^3.0.7
#   equatable: ^2.0.5
#   fancy_password_field: ^2.0.6
#   file_picker: ^6.0.0
#   firebase_core: ^2.27.0
#   firebase_messaging: ^14.7.19
#   flutter:
#     sdk: flutter

#   flutter_bloc: ^8.1.5
#   flutter_datetime_picker_plus: ^2.2.0
#   flutter_inappwebview: ^5.8.0
#   flutter_local_notifications: ^17.1.2
#   flutter_native_splash: ^2.3.5
#   flutter_pdfview: ^1.3.2
#   flutter_platform_widgets: ^6.1.0
#   flutter_spinkit: ^5.2.1
#   flutter_styled_toast: ^2.2.1
#   flutter_widget_from_html: ^0.15.0
#   gallery_saver: ^2.3.2
#   get_it: ^7.6.4
#   http: ^0.13.3
#   image_picker: ^1.0.8
#   injectable: ^2.3.2
#   injectable_generator: ^2.4.1
#   # location: ^4.4.0
#   location: ^6.0.2
#   # google_maps_widget: ^1.0.5+1
#   mask_text_input_formatter: ^2.9.0
#   modal_bottom_sheet:
#     git:
#       url: https://github.com/followthemoney1/modal_bottom_sheet.git
#       ref: main
#       path: modal_bottom_sheet
#   money_formatter: ^0.0.5
#   open_file_plus: ^3.4.1+1
#   package_info_plus: ^5.0.1
#   path_provider: ^2.1.3
#   pattern_formatter: ^3.0.0
#   pdf: ^3.10.8
#   permission_handler: ^11.3.1
#   photo_view: ^0.15.0
#   r_get_ip: ^0.1.3
#   responsive_framework: ^0.1.9
#   shared_preferences: ^2.2.3
#   shimmer: ^3.0.0
#   spreadsheet_decoder: ^2.2.0
#   sprintf: ^7.0.0
#   step_progress_indicator: ^1.0.2
#   # tab_container: ^2.0.0
#   tab_container: ^3.5.3
#   table_calendar: ^3.0.9
#   tiengviet: ^1.0.0
#   url_launcher: ^6.2.6
#   # geolocator: ^10.1.0
#   geolocator: ^10.1.1
#   # geolocator: ^13.0.1
#   # local_auth: ^2.1.8
#   local_auth: ^2.3.0
#   timeline_tile: ^2.0.0
#   # google_maps_flutter: ^2.6.1
#   google_maps_flutter: ^2.5.3
#   maps_launcher: ^2.2.1
#   qr_bar_code_scanner_dialog: ^0.0.5
#   collection: ^1.18.0
#   flutter_cache_manager: ^3.3.1
#   custom_sliding_segmented_control: ^1.8.3
#   expansion_tile_card: ^3.0.0
#   fl_chart: ^0.68.0
#   rxdart: ^0.27.7
#   flutter_screenutil: ^5.9.2
#   cached_network_image: ^3.3.1
#   device_preview: ^1.1.0
#   google_maps_routes: ^1.1.2
#   # socket_io_client: ^2.0.3+1
#   flutter_polyline_points: ^1.0.0
#   connectivity_plus: ^6.0.3
#   flutter_jailbreak_detection: ^1.10.0

# dev_dependencies:
#   flutter_launcher_icons: ^0.13.1
#   chewie: ^1.7.5
#   chewie_audio: ^1.5.0
#   flutter_lints: ^3.0.0
#   flutter_test:
#     sdk: flutter

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/app_icon/logo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21

# flutter_native_splash:
#   android: true
#   ios: true
#   web: false
#   color: "#0447a1"
#   image: assets/images/logo.png
#   android_12:
#     image: assets/images/splash_screen.png
#     android_gravity: center

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
#     - assets/icons/
#     - assets/lang/
#   fonts:
#     - family: Lato
#       fonts:
#         - asset: assets/fonts/Lato2OFL/Lato-Regular.ttf
#         - asset: assets/fonts/Lato2OFL/Lato-Bold.ttf
#           weight: 700

name: igls_new
description: iGLS Applications.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.29+55 #updated 29/10/2024

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.1
  build_runner: ^2.4.9
  cupertino_icons: ^1.0.8
  # currency_text_input_formatter: ^2.2.3
  currency_text_input_formatter: ^2.2.6
  # date_format: ^2.0.7
  date_format: ^2.0.9
  # device_info_plus: ^9.1.0
  device_info_plus: ^9.1.2
  # dio: ^4.0.6
  dio: ^5.7.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  # fancy_password_field: ^2.0.6
  fancy_password_field: ^2.0.7
  # file_picker: ^6.0.0
  file_picker: ^6.2.1
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.3
  flutter:
    sdk: flutter

  # flutter_bloc: ^8.1.5
  flutter_bloc: ^8.1.6
  flutter_datetime_picker_plus: ^2.2.0
  flutter_inappwebview: ^5.8.0
  # flutter_local_notifications: ^17.1.2
  flutter_local_notifications: ^17.2.4
  # flutter_native_splash: ^2.3.5
  flutter_native_splash: ^2.3.10
  # flutter_pdfview: ^1.3.2
  flutter_pdfview: ^1.3.4
  # flutter_platform_widgets: ^6.1.0
  flutter_platform_widgets: ^7.0.1
  flutter_spinkit: ^5.2.1
  flutter_styled_toast: ^2.2.1
  # flutter_widget_from_html: ^0.15.0
  flutter_widget_from_html: ^0.15.2
  gallery_saver: ^2.3.2
  get_it: ^7.6.7
  http: ^0.13.6
  # image_picker: ^1.0.8
  image_picker: ^1.1.2
  injectable: ^2.3.5
  injectable_generator: ^2.4.1
  # injectable_generator: ^2.5.1

  # location: ^4.4.0
  location: ^6.0.2
  # google_maps_widget: ^1.0.5+1
  mask_text_input_formatter: ^2.9.0
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  money_formatter: ^0.0.5
  open_file_plus: ^3.4.1+1
  package_info_plus: ^5.0.1
  # path_provider: ^2.1.3
  path_provider: ^2.1.4
  pattern_formatter: ^3.0.0
  # pdf: ^3.10.8
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  r_get_ip: ^0.1.3
  responsive_framework: ^0.1.9
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  # spreadsheet_decoder: ^2.2.0
  spreadsheet_decoder: ^2.3.0
  sprintf: ^7.0.0
  step_progress_indicator: ^1.0.2
  # tab_container: ^2.0.0
  tab_container: ^3.5.3
  table_calendar: ^3.0.9
  tiengviet: ^1.0.0
  # url_launcher: ^6.2.6
  url_launcher: ^6.3.1
  # geolocator: ^10.1.0
  geolocator: ^10.1.1
  # geolocator: ^13.0.1
  # local_auth: ^2.1.8
  local_auth: ^2.3.0
  timeline_tile: ^2.0.0
  # google_maps_flutter: ^2.6.1
  google_maps_flutter: ^2.5.3
  maps_launcher: ^2.2.1
  qr_bar_code_scanner_dialog: ^0.0.5
  collection: ^1.18.0
  flutter_cache_manager: ^3.3.1
  custom_sliding_segmented_control: ^1.8.3
  expansion_tile_card: ^3.0.0
  # fl_chart: ^0.68.0
  fl_chart: ^0.69.0
  rxdart: ^0.27.7
  # flutter_screenutil: ^5.9.2
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.3.1
  google_maps_routes: ^1.1.2
  # socket_io_client: ^2.0.3+1
  flutter_polyline_points: ^1.0.0
  connectivity_plus: ^6.0.3
  flutter_jailbreak_detection: ^1.10.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  chewie: ^1.7.5
  chewie_audio: ^1.5.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
# image_path: assets/app_icon/logo.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#0447a1"
  image: assets/images/logo.png
  android_12:
    image: assets/images/splash_screen.png
    android_gravity: center

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato2OFL/Lato-Regular.ttf
        - asset: assets/fonts/Lato2OFL/Lato-Bold.ttf
          weight: 700
